import Head from "next/head";
import React from "react";
import { Col, Row } from "antd";
import Navbar from "@/widget/navbar";
import PostsWidget from "@/widget/postsWidget";
import RightTab from "@/widget/rightTab";
import { useMediaQuery } from "@mui/material";
import UserPortfolio from "@/widget/leftTabWidget/userHoldings.jsx";
export default function Home() {
  const isMobileDevice = useMediaQuery("(max-width: 1000px)");

  return (
    <>
      <Head>
        <title>SocioCrypt | Decentralized Social Media App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/socio.png" />
        <link rel="x-icon" href="/socio.png" />
        <meta name="theme-color" content="#000000" />
      </Head>
      <Navbar />
      {!isMobileDevice && (
        <Row
          justify="center"
          style={{
            gap: "1rem",
            width: "100%",
            maxWidth: "1192px",
            margin: "0 auto",
          }}
        >
          <Col
            span={6}
            style={{
              position: "sticky",
              top: "calc(64px)",
              height: "700px",
            }}
          >
            <UserPortfolio />
            {/* <LeftTabWidget activeKey={"1"} /> */}
          </Col>
          <Col span={isMobileDevice ? 16 : 11}>
            <PostsWidget isProfile={false} />
          </Col>

          <Col
            span={6}
            style={{
              position: "sticky",
              top: "calc(  64px )",
              height: "700px",
            }}
          >
            <RightTab />
          </Col>
        </Row>
      )}
      {isMobileDevice && <PostsWidget isProfile={false} />}
    </>
  );
}
